// Generated by CoffeeScript 1.3.3
(function() {

  define(['./geometry'], function(geometry) {
    return {
      Entity: (function() {

        function _Class(x, y, shape) {
          this.x = x;
          this.y = y;
          this.shape = shape;
        }

        _Class.prototype.shapeSubpath = function(context, xoff, yoff) {
          this.shape.subpath(context, this.x + xoff, this.y + yoff);
        };

        _Class.prototype.boundsLeftOf = function(other) {
          return this.x + this.shape.bounds_offsets[1] < other.x + other.shape.bounds_offsets[0];
        };

        _Class.prototype.boundsIntersects = function(other) {
          var bounds_a, bounds_b;
          bounds_a = this.shape.bounds_offsets;
          bounds_b = other.shape.bounds_offsets;
          return this.x + bounds_a[0] <= other.x + bounds_b[1] && this.x + bounds_a[1] >= other.x + bounds_b[0] && this.y + bounds_a[2] <= other.y + bounds_b[3] && this.y + bounds_a[3] >= other.y + bounds_b[2];
        };

        _Class.prototype.intersects = function(other) {
          if (this.boundsIntersects(other)) {
            return geometry.intersects(this.x, other.x, this.y, other.y, this.shape, other.shape);
          }
          return false;
        };

        return _Class;

      })()
    };
  });

}).call(this);
