// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    paths: {
      'jquery': 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min'
    }
  });

  require(['jquery', 'game', 'loader', 'map', 'test'], function($, game, loader, map, test) {
    $(function() {
      var loader_scene;
      $.ajaxSetup({
        cache: false
      });
      loader_scene = new loader.LoaderScene({
        maps: {
          test: {
            name: 'test',
            script: test
          }
        },
        sprites: {
          test: 'test_sprite'
        },
        sounds: {
          test: 'sounds/jump.wav'
        }
      }, (function(loaded) {
        test.setTestSprite(loaded.sprites.test);
        test.setTestSound(loaded.sounds.test);
        game.switchScene(new map.MapScene(loaded.maps.test));
      }));
      game.init(320, 240, 1 / 60, 1 / 20, loader_scene);
      game.run();
    });
  });

}).call(this);
