// Generated by CoffeeScript 1.3.3
(function() {

  define(['./game'], function(game) {
    return {
      integrate: function(obj, dt) {
        var a, damping, inv_last_dt, last_x, last_y;
        inv_last_dt = game.invLastDt();
        last_x = obj.last_x || obj.x;
        last_y = obj.last_y || obj.y;
        a = obj.acceleration || [0, 0];
        damping = obj.damping || 1;
        obj.last_x = obj.x;
        obj.last_y = obj.y;
        obj.x = obj.x + (obj.x - last_x) * dt * inv_last_dt * damping + a[0] * dt * dt;
        obj.y = obj.y + (obj.y - last_y) * dt * inv_last_dt * damping + a[1] * dt * dt;
        obj.last_acceleration = a;
      },
      getVelocity: function(obj, dt) {
        var inv_last_dt, last_a, last_dt, last_x, last_y;
        last_dt = game.lastDt();
        inv_last_dt = game.invLastDt();
        last_x = obj.last_x || obj.x;
        last_y = obj.last_y || obj.y;
        last_a = obj.last_acceleration || [0, 0];
        return [(obj.x - last_x) * inv_last_dt + .5 * last_a[0] * last_dt, (obj.y - last_y) * inv_last_dt + .5 * last_a[1] * last_dt];
      },
      setVelocity: function(obj, v, dt) {
        var last_a, last_dt;
        last_dt = game.lastDt();
        last_a = obj.last_acceleration || [0, 0];
        obj.last_x = obj.x - (v[0] - .5 * last_a[0] * last_dt) * last_dt;
        obj.last_y = obj.y - (v[1] - .5 * last_a[1] * last_dt) * last_dt;
      }
    };
  });

}).call(this);
