// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', './util'], function($, util) {
    var url_prefix, url_suffix;
    url_prefix = 'sprites/';
    url_suffix = '.json';
    return {
      Sprite: (function() {

        function _Class(name, onload) {
          var cb_target;
          this.name = name;
          this.loaded = false;
          cb_target = this;
          $.getJSON(url_prefix + this.name + url_suffix, (function(data) {
            cb_target.load(data, onload);
          }));
          return;
        }

        _Class.prototype.load = function(json_data, onload) {
          var animation, animations, duration, frame, frames, image, name, sprite, _i, _len, _ref;
          frames = json_data.frames, animations = json_data.animations;
          for (name in animations) {
            animation = animations[name];
            duration = 0;
            _ref = animation.frames;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              frame = _ref[_i];
              duration += frame[1];
            }
            animations[name].duration = duration;
          }
          this.animations = animations;
          sprite = this;
          image = new Image();
          image.onload = function() {
            sprite.setupFrames(image, frames);
            this.loaded = true;
            return typeof onload === "function" ? onload() : void 0;
          };
          image.src = url_prefix + json_data.spritesheet;
        };

        _Class.prototype.setupFrames = function(img, frames) {
          var frame, grabFrame;
          grabFrame = function(frame) {
            var fcanvas, fctx, fh, fw;
            fw = frame.size[0];
            fh = frame.size[1];
            fcanvas = document.createElement('canvas');
            fcanvas.width = fw;
            fcanvas.height = fh;
            fctx = fcanvas.getContext('2d');
            fctx.drawImage(img, frame.pos[0], frame.pos[1], fw, fh, 0, 0, fw, fh);
            return fcanvas;
          };
          this.frames = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = frames.length; _i < _len; _i++) {
              frame = frames[_i];
              _results.push(grabFrame(frame));
            }
            return _results;
          })();
          this.frame_offsets = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = frames.length; _i < _len; _i++) {
              frame = frames[_i];
              _results.push(frame.offset);
            }
            return _results;
          })();
        };

        _Class.prototype.startAnimation = function(anim_name) {
          this.current_animation = this.animations[anim_name];
          this.animation_start_time = util.time();
        };

        _Class.prototype.draw = function(context, x, y, flip_h) {
          var anim_time, cur_anim, cur_anim_dur, frame, frame_img, frame_index, frame_offset, _i, _len, _ref;
          cur_anim = this.current_animation;
          cur_anim_dur = cur_anim.duration;
          frame_index = -1;
          anim_time = util.time() - this.animation_start_time;
          if (cur_anim.loop) {
            anim_time %= cur_anim_dur;
          } else if (anim_time > cur_anim_dur) {
            anim_time = cur_anim_dur;
          }
          _ref = cur_anim.frames;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            frame = _ref[_i];
            anim_time -= frame[1];
            if (anim_time <= 0) {
              frame_index = frame[0];
              break;
            }
          }
          frame_img = this.frames[frame_index];
          frame_offset = this.frame_offsets[frame_index];
          context.save();
          context.translate((x + .5) | 0, (y + .5) | 0);
          if (flip_h) {
            context.transform(-1, 0, 0, 1, 0, 0);
          }
          context.drawImage(frame_img, frame_offset[0], frame_offset[1]);
          context.restore();
        };

        return _Class;

      })()
    };
  });

}).call(this);
