// Generated by CoffeeScript 1.9.3
(function() {
  define(function() {
    return {
      default_buttons: {
        left: 37,
        up: 38,
        right: 39,
        down: 40,
        run: 16,
        jump: 90,
        debug: 192
      },
      init: function(buttons) {
        var button, results;
        this.buttons = buttons || this.default_buttons;
        results = [];
        for (button in this.buttons) {
          results.push(this[button] = {});
        }
        return results;
      },
      update: function() {
        var button, updateInputHash;
        updateInputHash = function(hash) {
          if (hash.state) {
            if (hash.last_state) {
              hash.pressed = false;
            } else {
              hash.pressed = true;
            }
          } else {
            if (hash.last_state) {
              hash.released = true;
            } else {
              hash.released = false;
            }
          }
          hash.last_state = hash.state;
        };
        for (button in this.buttons) {
          updateInputHash(this[button]);
        }
      },
      handleKeyDown: function(keyCode) {
        var bcode, button, ref;
        ref = this.buttons;
        for (button in ref) {
          bcode = ref[button];
          if (keyCode === bcode) {
            this[button].state = true;
          }
        }
      },
      handleKeyUp: function(keyCode) {
        var bcode, button, ref;
        ref = this.buttons;
        for (button in ref) {
          bcode = ref[button];
          if (keyCode === bcode) {
            this[button].state = false;
          }
        }
      }
    };
  });

}).call(this);
