// Generated by CoffeeScript 1.9.3
(function() {
  define(['./game'], function(game) {
    return {
      integrate: function(obj, dt) {
        var a, damping, last_a, v;
        v = obj.velocity || [0, 0];
        a = obj.acceleration || [0, 0];
        last_a = obj.last_acceleration || a;
        damping = obj.damping || 1;
        v[0] *= damping;
        v[1] *= damping;
        obj.x = obj.x + v[0] * dt + a[0] * dt * dt;
        obj.y = obj.y + v[1] * dt + a[1] * dt * dt;
        v[0] = v[0] + a[0] * dt;
        v[1] = v[1] + a[1] * dt;
        obj.velocity = v;
      }
    };
  });

}).call(this);
