// Generated by CoffeeScript 1.9.3
(function() {
  define(function() {
    var insertionSort, pNow;
    insertionSort = function(ary, cmp) {
      var i, j, k, ref, tmp;
      if (cmp == null) {
        cmp = function(a, b) {
          if (a < b) {
            return -1;
          } else if (a === b) {
            return 0;
          } else {
            return 1;
          }
        };
      }
      for (i = k = 1, ref = ary.length; 1 <= ref ? k < ref : k > ref; i = 1 <= ref ? ++k : --k) {
        tmp = ary[i];
        j = i;
        while (j > 0 && (cmp(ary[j - 1], tmp)) > 0) {
          ary[j] = ary[j - 1];
          --j;
        }
        ary[j] = tmp;
      }
    };
    (function() {
      var browserRaf, canceled, k, len, ref, targetTime, vendor, w;
      w = window;
      ref = ['ms', 'moz', 'webkit', 'o'];
      for (k = 0, len = ref.length; k < len; k++) {
        vendor = ref[k];
        if (w.requestAnimationFrame) {
          break;
        }
        w.requestAnimationFrame = w[vendor + 'RequestAnimationFrame'];
        w.cancelAnimationFrame = w[vendor + 'CancelAnimationFrame'] || w[vendor + "CancelRequestAnimationFrame"];
      }
      if (w.requestAnimationFrame) {
        if (w.cancelAnimationFrame) {
          return;
        }
        browserRaf = w.requestAnimationFrame;
        canceled = {};
        w.requestAnimationFrame = function(callback) {
          var id;
          return id = browserRaf(function(time) {
            if (id in canceled) {
              return delete canceled[id];
            } else {
              return callback(time);
            }
          });
        };
        w.cancelAnimationFrame = function(id) {
          return canceled[id] = true;
        };
      } else {
        targetTime = 0;
        w.requestAnimationFrame = function(callback) {
          var currentTime;
          targetTime = Math.max(targetTime + 16, currentTime = +(new Date));
          return w.setTimeout((function() {
            return callback(+(new Date));
          }), targetTime - currentTime);
        };
        w.cancelAnimationFrame = function(id) {
          return clearTimeout(id);
        };
      }
    })();
    pNow = (function() {
      var fallback, k, len, ref, time_offset, time_seen, vendor;
      time_offset = 0;
      time_seen = 0;
      fallback = function() {
        var t;
        t = Date.now();
        if (t < time_seen) {
          time_offset += time_seen - t;
        }
        time_seen = t;
        return t + time_offset;
      };
      if (typeof performance !== "undefined" && performance !== null) {
        if (performance.now != null) {
          return performance.now;
        }
        ref = ['ms', 'moz', 'webkit', 'o'];
        for (k = 0, len = ref.length; k < len; k++) {
          vendor = ref[k];
          pNow = performance[vendor + 'Now'];
          if (pNow != null) {
            return pNow;
          }
        }
      }
      return fallback;
    })();
    return {
      EPSILON: Math.pow(2, -50),
      time: function() {
        return .001 * pNow.call(window.performance);
      },
      persistentSort: insertionSort,
      constructBitmask: function(group_array) {
        var group, k, len, mask;
        mask = 0;
        for (k = 0, len = group_array.length; k < len; k++) {
          group = group_array[k];
          mask |= 1 << group;
        }
        return mask;
      },
      rgbToHex: function(r, g, b) {
        var toTwoDigitHex;
        toTwoDigitHex = function(v) {
          return ("00" + ((Math.min(Math.max(Math.round(v * 256), 0), 255)).toString(16))).substr(-2);
        };
        return "#" + (toTwoDigitHex(r)) + (toTwoDigitHex(g)) + (toTwoDigitHex(b));
      },
      prepareCoroutineSet: function(updateGenerator, drawGenerator) {
        var drawGen, updateGen;
        updateGen = updateGenerator();
        drawGen = drawGenerator();
        updateGen.next();
        drawGen.next();
        return {
          update: updateGen,
          draw: drawGen
        };
      }
    };
  });

}).call(this);
